### ISSUE TITLE
Boolean operations on shapes

### ISSUE THREAD

**Issue by RedHatter** [alexbol99/flatten-boolean-op#1]
This library is great for polygons but how do we preform Boolean operations on shapes other than polygons?

**Comment by alexbol99** [comment]
What do you mean by "shapes other than polygons"?

**Comment by RedHatter** [comment]
For example a `Circle` and a `Box`.

    let size = 100
    let circle = new Circle(new Point(size / 2, size / 2), 40)
    let box = new Box((size - 20) / 2, 20, (size + 20) / 2, size)
    let fullShape = unify(circle, box)

**Comment by alexbol99** [comment]
I understand your request. It makes sense, I will check what is the better way to implement it.

**Comment by alexbol99** [comment]
In version 0.6.5 of the flatten-js package `Circle` and `Box` may be added to the polygon as regular faces. 
So your task may be completed in the following way:
```
let {Polygon, Point, Circle, Box} = Flatten;
  let {unify, intersect, subtract} = BooleanOp;
  
  let size = 100
  let circle = new Circle(new Point(size / 2, size / 2), 40)
  let box = new Box((size - 20) / 2, 20, (size + 20) / 2, size)
  
  let poly_circle = new Polygon();
  let poly_box = new Polygon();
  poly_circle.addFace(circle);
  poly_box.addFace(box);
  
  let fullShape = unify(poly_circle, poly_box)
```
Please note that orientation of the face will always be counterClockwise (`Flatten.CCW`). Your can chain method `reverse()` with face creation if you need to revert orientation:
```
poly_circle.addFace(circle).reverse()
