### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by JanBaryla** [alexbol99/flatten-boolean-op#14]
I have been working with flatten-js for a while in Typescript and it has been performing very well. I have now decided that I'll also need to use this package for some operations. Unfortunately, this one doesn't expose static type definitions like the core package does.

Is there any chance this will be improved in the future?

**Comment by alexbol99** [comment]
Hi @JanBaryla.
Since couple of versions before, I moved boolean operations support to the core package `@flatten-js/core` and also added type definitions for Typescript. You'd better use it there.
I am not sure I will support this package for a long time.
Best,
Alex

**Comment by JanBaryla** [comment]
Ok, thanks for the feedback.
