### ISSUE TITLE
Infinite loop during subtraction op.

### ISSUE THREAD

**Issue by Saturn49** [alexbol99/flatten-boolean-op#3]
I ran across a case that seems to result in an infinite loop.  Sorry about the crazy numbers, it was found during debugging of a larger program and I just extracted the operations and numbers from the debugger.

https://beta.observablehq.com/@saturn49/boolean-operations-test-issue-3

Select Subtract (A minus B) and the browser tab will basically lock up.

--Nathan

**Comment by alexbol99** [comment]
Bug fixed in version 1.0.12
Thank you for cooperation
Best regards,
Alex

**Comment by Saturn49** [comment]
Thanks again Alex!  I tried 1.012 with flatten-js 0.6.6 and can confirm the issue is fixed.
