### ISSUE TITLE
Subtract does not clean edges

### ISSUE THREAD

**Issue by raplemie** [alexbol99/flatten-boolean-op#4]
Hi, we are starting to use this library and see some unexpected results, I'm not sure if this is "work as designed" so I thought mentioning it:

When subtracting a small polygon with a larger one, (the results being "nothing" remains) the polygon.isEmpty() method still reports that the polygon is not empty, because although it does not have any faces, it still has edges. Is it expected that the edges are not removed ?

I created a notebook, see the first box, and the "is Subtract(B, A) empty" result value.

https://beta.observablehq.com/@raplemie/boolean-operations-test-subtract-edges-issue

**Comment by alexbol99** [comment]
Hi, @raplemie 
Bug fixed in release v1.0.13
Now all edges removed as expected, *isEmpty()* returns *true*.
Thank you for cooperation.

**Comment by raplemie** [comment]
Quick fix really appreciated!
Thanks!
