### ISSUE TITLE
Subtract produces empty output in some cases

### ISSUE THREAD

**Issue by pentacular** [alexbol99/flatten-boolean-op#5]
In the following case, subtract produces what seems to be an empty output when the inputs overlap.

PS: It would be nice if there were an easier way to get the points out of a polygon. :)

Using  "@flatten-js/boolean-op": "^1.1.1",  "@flatten-js/core": "^1.0.15",

test("Bad case", t => {
  const baseZ0Surface = [[[8,2.4492935982947064e-16,0],[8.03842943919354,0.3901806440322572,0],[8.152240934977426,0.7653668647301798,0],[8.33706077539491,1.1111404660392044,0],[8.585786437626904,1.4142135623730951,0],[8.888859533960796,1.6629392246050907,0],[9.23463313526982,1.8477590650225735,0],[18.08658283817455,4.619397662556434,0],[19.02454838991936,4.903926402016152,0],[20,5,0],[20.97545161008064,4.903926402016152,0],[21.91341716182545,4.619397662556434,0],[22.77785116509801,4.157348061512726,0],[23.535533905932738,3.5355339059327373,0],[24.157348061512728,2.777851165098011,0],[24.619397662556434,1.913417161825449,0],[24.903926402016154,0.9754516100806412,0],[25,0,0],[24.90392640201615,-0.9754516100806436,0],[24.61939766255643,-1.913417161825452,0],[24.157348061512728,-2.777851165098011,0],[23.535533905932738,-3.5355339059327386,0],[22.77785116509801,-4.157348061512727,0],[21.91341716182545,-4.619397662556433,0],[20.97545161008064,-4.903926402016152,0],[20,-5,0],[19.024548389919357,-4.903926402016151,0],[18.08658283817455,-4.619397662556432,0],[9.234633135269819,-1.847759065022573,0],[8.888859533960796,-1.6629392246050905,0],[8.585786437626904,-1.414213562373095,0],[8.337060775394908,-1.111140466039204,0],[8.152240934977426,-0.7653668647301793,0],[8.03842943919354,-0.3901806440322567,0]]];
  const z0Surfaces = [[[[9,0,0],[8.827067523629074,1.7558128981451542,0],[8.31491579260158,3.444150891285808,0],[7.483226510722907,5.00013209717642,0],[6.3639610306789285,6.363961030678928,0],[5.0001320971764205,7.483226510722907,0],[3.4441508912858083,8.31491579260158,0],[1.755812898145155,8.827067523629074,0],[5.51091059616309e-16,9,0],[-1.7558128981451537,8.827067523629074,0],[-3.4441508912858074,8.31491579260158,0],[-5.000132097176418,7.483226510722908,0],[-6.363961030678928,6.3639610306789285,0],[-7.483226510722908,5.00013209717642,0],[-8.31491579260158,3.444150891285809,0],[-8.827067523629074,1.7558128981451575,0],[-9,1.102182119232618e-15,0],[-8.827067523629074,-1.7558128981451553,0],[-8.314915792601582,-3.444150891285807,0],[-7.4832265107229095,-5.000132097176418,0],[-6.363961030678929,-6.363961030678928,0],[-5.00013209717642,-7.483226510722907,0],[-3.444150891285813,-8.314915792601578,0],[-1.755812898145158,-8.827067523629072,0],[-1.6532731788489267e-15,-9,0],[1.7558128981451548,-8.827067523629074,0],[3.44415089128581,-8.31491579260158,0],[5.000132097176417,-7.4832265107229095,0],[6.363961030678926,-6.363961030678929,0],[7.483226510722907,-5.00013209717642,0],[8.314915792601578,-3.4441508912858136,0],[8.827067523629072,-1.7558128981451584,0]]]];
  const a = new Polygon();
  for (const polygon of baseZ0Surface) {
    a.addFace(polygon.map(([x, y]) => createPoint(x, y)));
  }
  const b = new Polygon();
  for (const surface of z0Surfaces) {
    for (const polygon of surface) {
      b.addFace(polygon.map(([x, y]) => createPoint(x, y)));
    }
  }
  const c = subtract(a, b);
  const result = [];
  for (const face of c.faces) {
    const polygon = [];
    for (const edge of face) {
      const start = edge.start;
      polygon.push([start.x, start.y, 0]);
    }
    result.push(polygon);
  }

  t.deepEqual(result, []);
});

**Comment by alexbol99** [comment]
Hello @pentacular ,

This issue is not a bug, it is a matter of polygon's orientation.
Both polygons in boolean operation have to be built based on same orientation - clockwise or counterclockwise. In your example the first polygon is oriented clockwise, and the second - counter clockwise. This is easy to fix using method ```polygon.reverse()```, like following:
```
// ensure all polygons have same orientation
let face = a.addFace(polygon.map(([x, y]) => new Point(x, y)));
 if (face.orientation() !== Flatten.ORIENTATION.CCW) {
    face.reverse();
 }
```

After fixing orientation, the result is correct, see this notebook: https://observablehq.com/d/5c5c6ad8fe76bb6c

And you can easy get polygon vertices using property ```vertices``` (getter):
```
let vertices = polygon.vertices
```

Thank you for reporting you problem

**Comment by pentacular** [comment]
Thanks for the quick diagnosis. :)

And I will be more careful to check orientation in the future.
