### ISSUE TITLE
two separate faces in one polygon after subtraction

### ISSUE THREAD

**Issue by wsarsenic** [alexbol99/flatten-boolean-op#9]
When surface with hole (the black one) subtracts another surface (the red one), we have a polygon with two separate surfaces.
I am expecting two polygons as the result.

Is there any misuse/misunderstanding here?

The surfaces:
![image](https://user-images.githubusercontent.com/2957264/63677824-6de8e900-c820-11e9-80e4-f8a24046f7d1.png)

The result:
![image](https://user-images.githubusercontent.com/2957264/63678137-244cce00-c821-11e9-90ba-90d0e07f4bdf.png)

Here is the code:
```
    let polygon1 = new Polygon();
    let p1 = point(20, 20);
    let p2 = point(20, -20); 
    let p3 = point(-20, -20) ;
    let p4 = point(-20, 20);
    let p5 = point(10, 10);
    let p6 = point(10, -10); 
    let p7 = point(-10, -10) ;
    let p8 = point(-10, 10);
    let p9 = point(30, 5);
    let p10 = point(30, -5); 
    let p11 = point(-30, -5) ;
    let p12 = point(-30, 5);

    let face1 = polygon1.addFace([p1, p2, p3, p4 ]);
    let face2 = polygon1.addFace([p5, p8, p7, p6 ]);

    let polygon2 = new Polygon();
    polygon2.addFace([p9, p10, p11, p12]);

    let res1 = subtract(polygon1, polygon2);
```

Thank you!

**Comment by alexbol99** [comment]
Hi, @wsarsenic 

Yes, the approach of this library is that the result of any boolean operation is a single polygon, possible comprised of several faces. I think this is convenient because you can use the result in any another actions you need.

Maybe you asking because you want to know that after subtraction you got several disjoint parts? I can add some functionality to make it easier to analyze if polygon comprised of several disjoint parts.

Best regards,
Alex

**Comment by wsarsenic** [comment]
@alexbol99 
Yes. I want to know how many parts (logically they are different polygons) after bool operation.
Could you help me on this?
Thank you!

**Comment by wsarsenic** [comment]
@alexbol99 Actually I want to know how many polygons are there and all the faces and edges for each polygon.
For example, after the while polygon (with a hole) subtracts red polygon, I could know there are two polygons. Polygon 1  is made of two faces (face 1 and face 2 ), while polygon 2 only has face 3, and every edges for each faces.

![image](https://user-images.githubusercontent.com/2957264/63735726-498a1c80-c8b3-11e9-8166-705503dec95c.png)

Could you add some functionality for this or tell me what to do?

Thank you!

**Comment by pentacular** [comment]
Hmm, I would have expected the polygon to only be constructed from disjoint faces.

Can there be faces in the resulting polygon that share edges if these weren't present in the input polygon?

**Comment by alexbol99** [comment]
Hi @pentacular ,

I would expect too, but I cannot prevent creation of polygon with touching or even intersected edges. If somebody only need to display polygon with touching faces, it is possible. It will be problematic to perform boolean operations or inclusion checks with such polygons.

Answering your you question: if there are two input polygons that share same edge, common (boundary) edges will be eliminated (or only one will left, depended on relation between them).

**Comment by alexbol99** [comment]
Hi @wsarsenic ,

I will consider adding function that separate polygon to an array of disjoint components.
Will it help?

Thanks,
Alex

**Comment by wsarsenic** [comment]
Hi @alexbol99 
1. If you mean faces of the same polygon by "disjoint components", then I would like it to be in order that the first is the outmost contour (island) and the rest are holes.

2. If you mean disjoint polygons by "disjoint components", and following structure of the result array is what I want:
```

Polygons:
│  Polygon 1
│   ├─ Face 1 (island)
│   ├─ Face 2 (hole)
│   │   ├─ Edge 1
│   │   └─ Edge 2
│   │
│  Polygon 2
│   └─ Face 1
│       └─ Edge 1
```

Thank you in advance!

**Comment by alexbol99** [comment]
Yes, this is exactly what I mean

**Comment by wsarsenic** [comment]
@alexbol99 
Deal~ ~

**Comment by alexbol99** [comment]
Supported in @flatten-js/core@v1.1.0
Added function ```polygon.splitToIslands()```
